#!/usr/bin/env bash
# Fixes server bug
sudo chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?)80/\18080/' /etc/nginx/sites-enabled/default
pkill apache2
# restart
sudo service nginx restart
