#!/usr/bin/env bash
# Fixing server bug
chmod 644 /etc/nginx/nginx.conf
sed -Ei 's/\s*#?\s*user .*/user nginx;/' /etc/nginx/nginx.conf
sed -Ei 's/(listen (\[::\]:)?8080) /\180 /' /etc/nginx/sites-enabled/default
pkill apache2
# restarting
sudo nginx -s /bin/bash -c 'service nginx restart'
